### ISSUE TITLE
Node6 got Path must be a string error.

### ISSUE THREAD

**Issue by greengerong** [mrak/stubby4node#57] opened 2016-05-27 12:12 UTC
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.getArgs (../node_modules/stubby/src/console/cli.js:141:38)
    at setupStartOptions (../node_modules/stubby/src/main.js:60:18)
    at Stubby.start (../node_modules/stubby/src/main.js:92:12)

Other node version works.

     $ node -v
      v6.1.0

**Comment by mrak** [comment] 2016-05-27 15:47
Thank you. This was fixed on `master` but not published. 

`0.3.1` should fix this.

**Closed by mrak** 2016-05-27 15:47 UTC

**Comment by wieringen** [comment] 2016-07-11 06:46
Still have this problem

node -v
v6.3.0

"stubby": "^0.3.1",

**Comment by mrak** [comment] 2016-07-22 05:18
@wieringen I'm not able to reproduce. Could you provide the full command you are using? Or if you are using the programmatic API, a code snippet that reproduces the error?

**Comment by mrak** [comment] 2016-07-29 02:15
Could you post the output of `stubby --version`?

If not installed globally: `./node_modules/.bin/stubby --version`?
